[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel", "gcc"]

[phases.install] 
cmds = [
  "pip install --upgrade pip --break-system-packages",
  "pip install -r requirements.txt --break-system-packages"
]

[start]
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"