[phases.setup]
nixPkgs = ["python311Full", "gcc"]

[phases.install] 
cmds = [
  "python3 -m pip install --upgrade pip --break-system-packages",
  "python3 -m pip install -r requirements.txt --break-system-packages"
]

[start]
cmd = "python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT"